name: CI/CD

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DISABLE_CHEATS: true

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.4
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: eslint
        run: pnpm run lint

      - name: typescript
        run: npx tsc

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm run build
          start: pnpm start

      - name: Build for Export
        env:
          NEXT_PUBLIC_BASE_PATH: /incremental-game-jam-2022
        run: pnpm run build

      - name: Export
        env:
          NEXT_PUBLIC_BASE_PATH: /incremental-game-jam-2022
        run: pnpm run export

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
