name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install Dependencies
        run: npm ci

      - name: eslint
        run: npm run lint

      - name: typescript
        run: npx tsc

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
